services:
  service_02:
    build: .
    ports:
      - "5001:80"
    volumes:
      - .:/code
    links:
      - service_02_mongodb
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
  service_02_mongodb:
    image: mongo:5.0
    volumes:
      - service_02_mongodb_container:/data/db
    logging:
        driver: none

volumes:
  service_02_mongodb_container:

networks:
  default:
    name: tarea_01
    external: true